### ISSUE TITLE
외래키라는것을 지원하는게 DBMS에서 일반적이지는 않은것인가요?

### ISSUE THREAD

**Issue by HaiSeong** [Chocochip101/DB-Study#8]
Real MySQL 4.2.1장에서 
'InnoDB가 외래키를 지원한다.',  'MyISAM은 안한다'  
"MyISAM은 외래키가 없으면 각각의 테이블마다 쿼리를 따로 날려야 하는건가?" 라는 의문이 들었어요.
외래키가 없다면 연관된 컬럼을 수동으로 각각 update insert 해주는 방식을 사용하는것일까요?
위의 방법이 좋다면 개발 환경에서는 외래키를 사용해서 편리하게 개발하고 나중에 수동으로 각각 쿼리를 날려주는 식으로 변경하는것도 좋은 방법일까요?

**Comment by Chocochip101** [comment]
> MyISAM은 외래키가 없으면 각각의 테이블마다 쿼리를 따로 날려야 하는건가?" 라는 의문이 들었어요.

외래키가 있어도 테이블마다 쿼리를 따로 날려야 하기 때문에, 어떤 의도로 작성하신 것인지 모르겠습니다.

> 위의 방법이 좋다면 개발 환경에서는 외래키를 사용해서 편리하게 개발하고 나중에 수동으로 각각 쿼리를 날려주는 식으로 변경하는것도 좋은 방법일까요?

외래키를 사용한다고 해서 개발 편리해지지는 않을 것 같아요. 매번 외래키 무결성 검사를 수행하기 때문에, 테이블이 많아지면 연관된 테이블의 삭제 순서를 조정해야 한다는 단점이 있어요.
